source_dir: "/vols/cms/ia2318/HiggsDNA-powheg/output/Run3_2024BTagging/Run3_2024/{channel}"

destination_dir: "/vols/cms/ia2318/REAL/data_January26/Run3_2024/{channel}_{ff_process}"

source_files:
  tt_data:
    - "Tau_Run2024C"
    - "Tau_Run2024D"
    - "Tau_Run2024E"
    - "Tau_Run2024F"
    - "Tau_Run2024G"
    - "Tau_Run2024H"
    - "Tau_Run2024I_v1"
    - "Tau_Run2024I_v2"
  mt_data:
    - "Muon0_Run2024C"
    - "Muon0_Run2024D"
    - "Muon0_Run2024E"
    - "Muon0_Run2024F"
    - "Muon0_Run2024G"
    - "Muon0_Run2024H"
    - "Muon0_Run2024I_v1"
    - "Muon0_Run2024I_v2"
    - "Muon1_Run2024C"
    - "Muon1_Run2024D"
    - "Muon1_Run2024E"
    - "Muon1_Run2024F"
    - "Muon1_Run2024G"
    - "Muon1_Run2024H"
    - "Muon1_Run2024I_v1"
    - "Muon1_Run2024I_v2"
  et_data:
    - "EGamma0_Run2024C"
    - "EGamma0_Run2024D"
    - "EGamma0_Run2024E"
    - "EGamma0_Run2024F"
    - "EGamma0_Run2024G"
    - "EGamma0_Run2024H"
    - "EGamma0_Run2024I_v1"
    - "EGamma0_Run2024I_v2"
    - "EGamma1_Run2024C"
    - "EGamma1_Run2024D"
    - "EGamma1_Run2024E"
    - "EGamma1_Run2024F"
    - "EGamma1_Run2024G"
    - "EGamma1_Run2024H"
    - "EGamma1_Run2024I_v1"
    - "EGamma1_Run2024I_v2"
  mc:
    - "DYto2E_MLL_50_amcatnloFXFX"
    - "DYto2Mu_MLL_50_amcatnloFXFX"
    - "DYto2Tau_MLL_50_amcatnloFXFX"
    - "WtoENu_madgraphMLM"
    - "WtoMuNu_madgraphMLM"
    - "WtoTauNu_madgraphMLM"
    - "TTto2L2Nu"
    - "TTtoLNu2Q"
    - "WW"
    - "WZ"
    - "ZZ"
    - "ST_tW_top_2L2Nu"
    - "ST_tW_antitop_2L2Nu"
    - "ST_tW_top_LNu2Q"
    - "ST_tW_antitop_LNu2Q"
    
